### ISSUE TITLE
Removing those interested in future seasons from queries

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#16]
When we move someone from incompletes or pre-registered applicants to future seasons, they still show up in the query. Is there a way to make either a new query where these applicants are removed or edit it so they no longer show up in that query? I want to make sure that for blast emails, we do not email those who have already told us that they are not interested in this round. Thanks for your help!

**Comment by IshaDakota** [comment]
what I would recommend is that we set it up so that if you mark them as cancelled, they get removed from the query. Sound good?

**Comment by Shorashim** [comment]
Sounds good to me!

**Comment by Shorashim** [comment]
Hi Adam! Just wanted to check in about this and when these applicants will start being removed from the list? I just checked pre-registration and found a few that wanted future seasons. Since we want to be able to send mass texts and emails this week, I want to ensure that it is up-to-date. Thanks!

**Comment by IshaDakota** [comment]
applicants that are cancelled will now not appear in the preregistered and incomplete queries.

**Comment by Shorashim** [comment]
No deposit too? Thanks!!

**Comment by IshaDakota** [comment]
link to the query?

**Comment by Shorashim** [comment]
http://brireg.israelwithisraelis.com/query_handler.php?query_id=0671&sort=last_name,%20first_name

and

http://brireg.israelwithisraelis.com/query_handler.php?query_id=0740&sort=last_name,%20first_name

**Comment by IshaDakota** [comment]
@Shorashim so for those it is better to make a query that specifically removes the cancelled applicants rather than setting up to do so by default. There are cases where you would want cancelled applicants in the query, for instance, on the "did not travel" queries/\.

This can be written in the query by adding "AND appended.decline != 'Y' "

**Comment by Shorashim** [comment]
Zach, don't you not cancel this early on?

**Comment by Shorashim** [comment]
@IshaDakota ineligible applications are still showing up in the incomplete query. Can we please update this? Thanks so much!

**Comment by IshaDakota** [comment]
>ineligible applications are still showing up in the incomplete query. 

@Shorashim This does not have to do with this issue + it is closed.

If there is a new issue, please open a new issue, if there is an old issue that has a  problem, please re-open that issue.
