### ISSUE TITLE
Date Choice Edit

### ISSUE THREAD

**Issue by zpellish** [MarchingLizard/brifony#19]
Adam,

Can you add to the end of date_id choice 430 (Ultimate Adventure with Israelis: OC WAY) in the drop down, (LAX Departure). You did this for a different trip, and the same way as before is perfect. Thank you.

**Comment by IshaDakota** [comment]
done

**Comment by zpellish** [comment]
Adam,

This must have not saved because it is not appearing in the application.

**Comment by IshaDakota** [comment]
hmmm.. weird. OK, open again if there are any problems.
