### ISSUE TITLE
Interviews Not Saving

### ISSUE THREAD

**Issue by zpellish** [MarchingLizard/brifony#20]
Adam

BriReg is not saving interviews and when we hit the update record button it takes a while to process and then shows a blank white screen and the interview isn't saved.

**Comment by IshaDakota** [comment]
is that new?

**Comment by IshaDakota** [comment]
@zpellish please confirm that this is either a new issue or an ongoing issue. I tested on a previous applicant in round 32 and it seems to work as expected.

**Comment by zpellish** [comment]
This is a new issue as of this morning.

On Tue, Feb 9, 2016 at 10:09 AM, Adam Stewart <notifications@github.com>
wrote:

> @zpellish <https://github.com/zpellish> please confirm that this is
> either a new issue or an ongoing issue. I tested on a previous applicant in
> round 32 and it seems to work as expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/20#issuecomment-181932491>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel *
*with Shorashim this summer!*

**Comment by IshaDakota** [comment]
@zpellish I'm thinking maybe it was a temporary sever issue... can you give me an applicant it was failing on?

**Comment by zpellish** [comment]
It wasn't working on Mallory Sonenthal, but after three tries it worked.

On Tue, Feb 9, 2016 at 10:14 AM, Adam Stewart <notifications@github.com>
wrote:

> @zpellish <https://github.com/zpellish> I'm thinking maybe it was a
> temporary sever issue... can you give me an applicant it was failing on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/20#issuecomment-181935796>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel *
*with Shorashim this summer!*
