### ISSUE TITLE
Applications Not Transferring From Regadmin To BriReg/Deposits Not Showing Up In BriReg

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#21]
1. Jake Rubenstein
2. Jenna Frankel
3. Lindsay Doloboff
4. Stacey Cotter
5. Aaron Ivanhoe
6. Katharine Parissenti  
7. Dana Heyman
8. Madeline Kaufman
9. Steve Shapin
10. Chase Berman
11. Liza Berkelhamer
12. Lindsay Peltin
13. Rachel Stone
14. Michael Raymond

There are a few more, but still trying to figure out who they are.

**Comment by IshaDakota** [comment]
#12

**Comment by Shorashim** [comment]
Dana Heyman (Says no deposit, but it is marked 2/1/16)
Madeline Kaufman (still does not show up in BRIREG)

**Comment by Shorashim** [comment]
Previous issue regarding Dana Heyman and Madeline Kaufman not yet rectified.

**Comment by IshaDakota** [comment]
Let's leave this in #12 because it has the most history.
