### ISSUE TITLE
Order of flights

### ISSUE THREAD

**Issue by zpellish** [MarchingLizard/brifony#22]
Adam,

This isn't urgent but may cause me a headache down the line. I have been entering flights into BriReg as I've assigned them, however this is not chronologically. Is there a simple way to reorder the flights at some point without messing up with data already entered?

**Comment by IshaDakota** [comment]
Yes. The purpose of changing the date field to an actual date (rather than text) was so that we could order on the departure date. We just forgot to add the actual sorting. Easy fix for today.

**Comment by zpellish** [comment]
Perfect. Let me know when it's been updated. Thanks Adam!

On Fri, Feb 12, 2016 at 5:51 AM, Adam Stewart <notifications@github.com>
wrote:

> Yes. The purpose of changing the date field to an actual date (rather than
> text) was so that we could order on the departure date. We just forgot to
> add the actual sorting. Easy fix for today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/22#issuecomment-183293216>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel *
*with Shorashim this summer!*

**Comment by IshaDakota** [comment]
see: http://brireg.israelwithisraelis.com/flights_table.php

Ordered by date and flight time.

**Comment by zpellish** [comment]
Thank you for putting them in order, but I haven't entered all of the
flights yet. Is there a way I can reorder them chronologically at another
time, or is that only something you can do?

On Mon, Feb 15, 2016 at 2:34 PM, Adam Stewart <notifications@github.com>
wrote:

> Closed #22 <https://github.com/MarchingLizard/brifony/issues/22>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/22#event-551182543>.
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel trips*
*with Shorashim this summer!*

**Comment by IshaDakota** [comment]
It will order automatically based on the outgoing departure date and time.

**Comment by zpellish** [comment]
Amazing! As always you're the greatest Adam.

On Mon, Feb 15, 2016 at 3:53 PM, Adam Stewart <notifications@github.com>
wrote:

> It will order automatically based on the outgoing departure date and time.
>
> On Monday, February 15, 2016, zpellish <notifications@github.com> wrote:
>
> > Thank you for putting them in order, but I haven't entered all of the
> > flights yet. Is there a way I can reorder them chronologically at another
> > time, or is that only something you can do?
> >
> > On Mon, Feb 15, 2016 at 2:34 PM, Adam Stewart <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Closed #22 <https://github.com/MarchingLizard/brifony/issues/22>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/MarchingLizard/brifony/issues/22#event-551182543>.
> > >
> >
> >
> >
> > --
> > Zach Pellish
> > North American Operations Manager
> > Shorashim
> > Main line: 312-267-0677
> > Direct line: 312-380-6536
> >
> > *APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel trips*
> > *with Shorashim this summer!*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MarchingLizard/brifony/issues/22#issuecomment-184408806
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/22#issuecomment-184410410>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel trips*
*with Shorashim this summer!*
