### ISSUE TITLE
Status Page Password Reset

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#24]
Currently drawing an error. Can this be fixed?

**Comment by IshaDakota** [comment]
![screen shot 2016-02-19 at 10 01 22 am](https://cloud.githubusercontent.com/assets/688507/13185109/0bb8ffaa-d705-11e5-836e-69be3fb51ed3.png)

**Comment by IshaDakota** [comment]
This should be fixed, marking as closed Can't exactly test it on live so if it happens again, reopen the issue.
