### ISSUE TITLE
Removing Ineligible & Interest in Future Seasons from No Deposit, Incomplete, and Pre-registered Applicants Queries

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#25]
From what I have noticed, these still seem to be showing up in the query.

Examples No Deposit/Not Yet Deposited:
-Future season - Melissa Andren & Alexander Balkan

Example Pre-Reg:
-Future Season - Amanda Johnson

Examples Incomplete:
-Not Eligible - Dali Adelman

Please let me know if you need more information.

**Comment by IshaDakota** [comment]
None of these is being removed because non of them marked as cancelled. This is the way we agreed we would handle this per #16:

> IshaDakota commented 16 days ago
> what I would recommend is that we set it up so that if you mark them as cancelled, they get removed from the query. Sound good?

> Shorashim commented 16 days ago
> Sounds good to me!

**Comment by Shorashim** [comment]
Thank you! So sorry about that. We are all set.
