### ISSUE TITLE
Flights in Military Time for Applicants

### ISSUE THREAD

**Issue by zpellish** [MarchingLizard/brifony#29]
Adam,

I am entering the flight times in military time as you suggested into the flight table, and BriReg is correctly converting it to 12hr time when displaying the flight table. However, in the participant side of the Application Status Page the times are displaying as military time in the flight table. An example of two applicants where this issue is happening is Rachel Bass or Lily Boyar are two I've found. I tried attaching a screen shot to this issue, but it wasn't displaying.

**Comment by IshaDakota** [comment]
Fixed. See below:

<img width="854" alt="application_status_page___application_status___birthright_israel__shorashim" src="https://cloud.githubusercontent.com/assets/688507/13417277/d6ecdf52-df2f-11e5-8c09-fa057c704c4c.png">
