### ISSUE TITLE
Third Date Choice

### ISSUE THREAD

**Issue by zpellish** [MarchingLizard/brifony#3]
Adam,

Applicants are entering their third date choice, but it is not appearing in BriReg on our side of it. Every application I have looked at has the third date choice blank despite the fact that they entered it.

**Comment by IshaDakota** [comment]
How do you know they are entering it? Are they telling you? Because there are some that have date all choices made. See below:

![shorashim_birthright_israel_registration_database](https://cloud.githubusercontent.com/assets/688507/12724808/3893c296-c8d5-11e5-820d-1e1fdb952ee5.png)

But I need to figure out if it's a case of the choice not being recorded, or if it's a case of requiring a third date choice being enforced.

**Comment by zpellish** [comment]
I was logging in as them and viewing it from the applicant side.

On Mon, Feb 1, 2016 at 11:38 AM, Adam Stewart <notifications@github.com>
wrote:

> How do you know they are entering it? Are they telling you? Because there
> are some that have date all choices made. See below:
>
> [image: shorashim_birthright_israel_registration_database]
> <https://cloud.githubusercontent.com/assets/688507/12724808/3893c296-c8d5-11e5-820d-1e1fdb952ee5.png>
>
> But I need to figure out if it's a case of the choice not being recorded,
> or if it's a case of requiring a third date choice being enforced.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/3#issuecomment-178088981>
> .
>



-- 

Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536


*Click here to pre-register <http://bit.ly/1USYrzo> for future *
*Birthright Israel: **Shorashim trips!*

**Comment by IshaDakota** [comment]
OK... give me the name of someone for who it didn't record and which choice you were trying to make.

**Comment by zpellish** [comment]
Julia Addis

On Mon, Feb 1, 2016 at 11:46 AM, Adam Stewart <notifications@github.com>
wrote:

> OK... give me the name of someone for who it didn't record and which
> choice you were trying to make.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/3#issuecomment-178092051>
> .
>



-- 

Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536


*Click here to pre-register <http://bit.ly/1USYrzo> for future *
*Birthright Israel: **Shorashim trips!*

**Comment by IshaDakota** [comment]
I have worked up a fix for this, but want to be sure about how you want to resolve. Do you want to send an email to all of the people who did not have their choice recorded to send them back to appstatus?

**Comment by IshaDakota** [comment]
This is fixed... I'm closing but waiting for your solution for people ho did not have dates recorded.
