### ISSUE TITLE
Itamar Mahal

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#31]
Itamar has two applications under the same email address.

The application with the ID of 689190433698 is the correct application, which shows up when you search in Bri34 in RegAdmin. His application under the ID of 432720433449 needs to be deleted, as notated in the 
RegAdmin system (https://regadmin.birthrightisrael.com/ApplicantRecord.cfm?idm=3340272&idr=-34&b=v). Although he does not show up in 34 (it shows up as -34 in RegAdmin), he shows up when you search all rounds:
Good app RegAdmin:
![screen shot 2016-03-08 at 8 44 46 am](https://cloud.githubusercontent.com/assets/13404688/13604793/0a0564f6-e50a-11e5-9d1b-31962e2471fe.png)

Bad app Regadmin:
![screen shot 2016-03-08 at 8 43 02 am](https://cloud.githubusercontent.com/assets/13404688/13604779/f69b65d2-e509-11e5-8177-dfe3b6eeb789.png)

Both apps are currently showing up in brireg. Although I cancelled the "bad app", this application is preventing Itamar from being able to login to his secondary application and complete it. He completed his secondary application in the "bad app" and we need it to show up in the correct app.

Since, somehow, both apps are under the same email, whenever Itamar tries to login, it tells him that his deposit has not been submitted. In other words, it is pulling the incorrect application and information when he logs in.

Good app BriReg:
![screen shot 2016-03-08 at 8 47 44 am](https://cloud.githubusercontent.com/assets/13404688/13604869/763e4ea8-e50a-11e5-9bc4-31532bbf44fd.png)

Bad app BriReg:
![screen shot 2016-03-08 at 8 48 16 am](https://cloud.githubusercontent.com/assets/13404688/13604874/88c6b754-e50a-11e5-9b8c-7e44d6412483.png)

Status update:
![screen shot 2016-03-08 at 8 46 53 am](https://cloud.githubusercontent.com/assets/13404688/13604850/61ad31a2-e50a-11e5-9f13-f473cdfa50ea.png)

What is the best way to proceed in rectifying this? Please let me know if you need any more info. Thank you!

**Comment by IshaDakota** [comment]
this should rectify when BRI removes the duplicate.

**Comment by Shorashim** [comment]
From Flora: "The wrong ID (432720433449) was deleted on 2/16/16 and the round was set to -34. So it no longer exists in round 34 on our side. Not sure why it's giving you a problem in your secondary system. Anyway, just in case, We changed the email address of the deleted record to itamarmahal94_DELETED@gmail.comso that it no longer matches the correct record. Again, no idea how your secondary system works, and why it didn't pick up that the record was actually deleted from round 34 on 2/16. You should definitely look into it."

The second application is still within brireg. Any other ideas of what we can do? Thanks!

**Comment by IshaDakota** [comment]
@Shorashim did this resolve?

**Comment by Shorashim** [comment]
It has not. Flora said they had done everything on Birthright's end and have tried everything I can think of. Is there a way to manually delete the bad application, in its entirety, from BriReg?
