### ISSUE TITLE
Pre-Registrations - Transferring from RegAdmin to BriReg

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#32]
I am not sure if this is the same error as with incompletes, but some pre-registrations are also not transferring over. 

For example, Jamie Hoffmann (ID: 454580723256) is not showing up in BriReg at all. She has not been cancelled or moved to another season. In comparison, Julia Arnold (ID: 271811623767) also pre-registered, but shows up in both systems.

If you need more info on my end, please let me know!

**Comment by IshaDakota** [comment]
yep. same issue. now fixed
