### ISSUE TITLE
Roster Update

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#36]
Requested updated fields for when bus rosters are exported:

-Notes
-Summer Camp
-Fraternity 
-Youth Group
-Day School
-Friendship Requests
-Essay 1
-Essay 2

**Comment by IshaDakota** [comment]
Done.

@Shorashim please test and close if satisfactory.

**Comment by Shorashim** [comment]
I apologize if there was confusion. Can this be added in the full roster rather than the trip roster? We pull this information for recruiting purposes, so we need the university, city, state, email, gender, etc. that is included on the full roster export list.

**Comment by IshaDakota** [comment]
@Shorashim updated, please check

**Comment by Shorashim** [comment]
All good. Thank you!
