### ISSUE TITLE
Camps showing up incorrectly

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/brifony#5]
Many of the applicant's camp affiliation is showing up as "Camp Romaca" rather than what they chose

![screen shot 2016-02-01 at 1 50 32 pm](https://cloud.githubusercontent.com/assets/13404688/12729135/d8c497bc-c8ea-11e5-823b-1df7343096c4.png)

**Comment by IshaDakota** [comment]
do we know for sure that they are choosing something else?

**Comment by zpellish** [comment]
I spoke to someone who said when he chose other for his camp it auto
populated to Camp Romaca

On Mon, Feb 1, 2016 at 4:59 PM, Adam Stewart <notifications@github.com>
wrote:

> do we know for sure that they are choosing something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/5#issuecomment-178242572>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel *
*with Shorashim this summer!*

**Comment by IshaDakota** [comment]
That was extremely helpful. Problem is fixed.

For the people who have Camp Romaca as their camp... that data is bad. Do we want to email them and ask them to re-enter their camp info?

A

**Comment by Shorashim** [comment]
That sounds like a good idea. Is that something that you set up or that we do? Thanks for your help!

**Comment by IshaDakota** [comment]
you would have to email everyone who chose Camp Romaca. (campid=127)

**Comment by IshaDakota** [comment]
I'm closing this because your answer here doesn't impact the solution.
