### ISSUE TITLE
Switched out of Shorashim

### ISSUE THREAD

**Issue by zpellish** [MarchingLizard/brifony#8]
Adam,

Is there a way to add a flag on someone's application in BriReg when they have switched out of Shorashim? In previous rounds it would show at the top under the eligibility field. An example of someone that has switched out is Drew Ansbacher.

**Comment by IshaDakota** [comment]
So in a way, we already have this. See for instance,

<img width="1117" alt="shorashim_birthright_israel_registration_database" src="https://cloud.githubusercontent.com/assets/688507/12804032/db97e158-cab4-11e5-9d05-84a4c180a66d.png">

The problem with Drew, is that he switched out before his application was complete, so he's sort of like a ghost. I think we could re-engineer this in a way that captured him as switching out, but I think it's something we would need to save for next round (unless you think it's crucial, and we can spend some time figuring out how to run an update on the data).

**Comment by zpellish** [comment]
I don't think it's crucial unless we start to notice a large number of
applicants that are falling into this category.

On Wed, Feb 3, 2016 at 8:32 PM, Adam Stewart <notifications@github.com>
wrote:

> So in a way, we already have this. See for instance,
>
> [image: shorashim_birthright_israel_registration_database]
> <https://cloud.githubusercontent.com/assets/688507/12804032/db97e158-cab4-11e5-9d05-84a4c180a66d.png>
>
> The problem with Drew, is that he switched out before his application was
> complete, so he's sort of like a ghost. I think we could re-engineer this
> in a way that captured him as switching out, but I think it's something we
> would need to save for next round (unless you think it's crucial, and we
> can spend some time figuring out how to run an update on the data).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/8#issuecomment-179583872>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel *
*with Shorashim this summer!*

**Comment by IshaDakota** [comment]
ok... let's re-open in that case
