### ISSUE TITLE
Assigning to flights

### ISSUE THREAD

**Issue by zpellish** [MarchingLizard/brifony#9]
Adam,

When I go to assign someone (at the bottom of a query) the drop down menu where all the flights usually appear shows the error '.$groupid.'. I have entered a few flights in the flight table already, but is there something I'm not doing to sync this list with the flight table?

**Comment by IshaDakota** [comment]
nope, you did everything right. That was a bug - now fixed.

The only thing to be careful of is that you give the group name EXACTLY as it appears in the BRI system. That's how it matched people with flights they have been assigned to.

**Comment by IshaDakota** [comment]
actually, you did make one mistake... you should enter the times as HH:MM with the 24-hour clock and without AM PM. They are going to show up wrong in the app status the way they are entered now.

Other wise they look good

**Comment by zpellish** [comment]
Just to be clear I need to make sure the affiliation (Ultimate Adventure
with Israelis: JUF Chicago Community Trip - Graduates and Professionals)
needs to match exactly with RegAdmin? We've shortened the affiliations in
the past and made them different without being an issue.

Also, when you say matched the flights people have been assigned to are you
saying within BriReg, or for the "Participants to be assigned to a flight"
query?

On Wed, Feb 3, 2016 at 8:25 PM, Adam Stewart <notifications@github.com>
wrote:

> nope, you did everything right. That was a bug - now fixed.
>
> The only thing to be careful of is that you give the group name EXACTLY as
> it appears in the BRI system. That's how it matched people with flights
> they have been assigned to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/9#issuecomment-179580017>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel *
*with Shorashim this summer!*

**Comment by IshaDakota** [comment]
no, sorry. you need the groupid to match. SH-XX-XXX.

The other fields you can name however you want.

The groupid matches it to the BRI system so that when we pull data it knows which flight they have been assigned to.

**Comment by zpellish** [comment]
Ok perfect thanks Adam.

On Thu, Feb 4, 2016 at 9:12 AM, Adam Stewart <notifications@github.com>
wrote:

> no, sorry. you need the groupid to match. SH-XX-XXX.
>
> The other fields you can name however you want.
>
> The groupid matches it to the BRI system so that when we pull data it
> knows which flight they have been assigned to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarchingLizard/brifony/issues/9#issuecomment-179891455>
> .
>



-- 
Zach Pellish
North American Operations Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6536

*APPLY NOW <http://bit.ly/1USYrzo> for **Birthright Israel *
*with Shorashim this summer!*
